services:
  # postgres:
  #   container_name: postgres
  #   image: postgres
  #   environment:
  #     POSTGRES_PASSWORD: apipassword
  #     # POSTGRES_USER: escrow
  #     POSTGRES_DB: escrow
  #   ports:
  #     - "5432:5432"
  #   volumes:
  #     - ./data:/var/lib/postgresql/data
  #   healthcheck:
  #     test: ["CMD-SHELL", "pg_isready"]
  #     interval: 10s
  #     timeout: 5s
  #     retries: 5
  #   networks:
  #     - local

  tigerbeetle:
    container_name: tigerbeetle
    image: ghcr.io/tigerbeetle/tigerbeetle
    # command: "sh -c './tigerbeetle format --cluster=0 --replica=0 /data/0_0.tigerbeetle'"
    # command: "start --addresses=0.0.0.0:3000 /data/0_0.tigerbeetle --cache-grid=256MiB"
    command: "format --cluster=0 --replica=0 --replica-count=1 /data/0_0.tigerbeetle"
    volumes:
      - ./data:/data/0_0.tigerbeetle
    privileged: true
    security_opt:
      - "seccomp=unconfined"
    ports:
      - "3000:3000"
      # - "3001:3001"
      # - "3002:3002"
    # network_mode: host
    cap_add:
      - IPC_LOCK
    # restart: always
    networks:
      - local

  # backend:
  #   container_name: escrow-backend
  #   build:
  #     context: .
  #     dockerfile: Dockerfile
  #   environment:
  #     DATABASE_URL: postgres://postgres:apipassword@postgres:5432/escrow
  #     PORT: "8080"
  #     CLOUDINARY_SECRET_KEY: "UBBXphzGtWg8KbJ8wPN4-p-_lQQ"
  #     CLOUDINARY_API_KEY: "157714545362732"
  #     CLOUDINARY_CLOUD_NAME: "dgetio8s1"
  #     CLOUDINARY_FOLDER: "garage-profile-pictures"
  #   ports:
  #     - "8080:8080"
  #   depends_on:
  #     - postgres
  #     - tigerbeetle
  #   networks:
  #     - local

volumes:
  postgres-data:
  tigerbeetle-data:
  escrow-backend-data:

networks:
  local:
    driver: bridge
