name: Deploy Production

on:
  push:
    branches: [main]

jobs:
  deployments:
    name: ESCROW Production
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Building & Pushing GHCR Image
      run: |
        docker login -u ${{ secrets.GHCR_USERNAME }} -p ${{ secrets.GHCR_TOKEN }} ghcr.io
        docker build -t ghcr.io/wigxel/escrow-backend:${{ github.sha }} . --no-cache
        docker push ghcr.io/wigxel/escrow-backend:${{ github.sha }}

    # - name: Deploying To Staging Server
    #   run: |
    #     install -m 600 -D /dev/null ~/.ssh/id_rsa
    #     echo "${{ secrets.SSH_PRIVATE_KEY }}" > ~/.ssh/id_rsa
    #     echo "${{ secrets.SSH_CONFIG }}" > ~/.ssh/config
    #     ssh bumpa-storefront-themes -tt ./storefront.sh ${{ github.sha }}
    #     ssh bumpa-storefront-themes -tt ./deployment.sh
